steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/${PROJECT_ID}/weather-app', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/weather-app']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'weather-app', '--image', 'gcr.io/${PROJECT_ID}/weather-app', '--platform', 'managed', '--region', 'us-central1']
