let locations = [
    {
        city: "Dar es Salaam",
        admin: "",
        country: "Tanzania",
        population_proper: "2698652",
        iso2: "TZ",
        capital: "primary",
        lat: "-6.8",
        lng: "39.283333",
        population: "2930000"
    },
    {
        city: "Moshi",
        admin: "Kilimanjaro",
        country: "Tanzania",
        population_proper: "206728",
        iso2: "TZ",
        capital: "admin",
        lat: "-3.35",
        lng: "37.333333",
        population: "721018"
    },
    {
        city: "Mwanza",
        admin: "Mwanza",
        country: "Tanzania",
        population_proper: "436801",
        iso2: "TZ",
        capital: "admin",
        lat: "-2.516667",
        lng: "32.9",
        population: "493944"
    },
    {
        city: "Zanzibar",
        admin: "Zanzibar Urban/West",
        country: "Tanzania",
        population_proper: "373220",
        iso2: "TZ",
        capital: "admin",
        lat: "-6.166667",
        lng: "39.183333",
        population: "403658"
    },
    {
        city: "Arusha",
        admin: "Arusha",
        country: "Tanzania",
        population_proper: "320074",
        iso2: "TZ",
        capital: "admin",
        lat: "-3.366667",
        lng: "36.683333",
        population: "341136"
    },
    {
        city: "Mbeya",
        admin: "Mbeya",
        country: "Tanzania",
        population_proper: "232062",
        iso2: "TZ",
        capital: "admin",
        lat: "-8.9",
        lng: "33.45",
        population: "291649"
    },
    {
        city: "Morogoro",
        admin: "Morogoro",
        country: "Tanzania",
        population_proper: "234535",
        iso2: "TZ",
        capital: "admin",
        lat: "-6.816667",
        lng: "37.666667",
        population: "250902"
    },
    {
        city: "Tanga",
        admin: "Tanga",
        country: "Tanzania",
        population_proper: "209435",
        iso2: "TZ",
        capital: "admin",
        lat: "-5.066667",
        lng: "39.1",
        population: "224876"
    },
    {
        city: "Dodoma",
        admin: "",
        country: "Tanzania",
        population_proper: "180541",
        iso2: "TZ",
        capital: "primary",
        lat: "-6.183333",
        lng: "35.75",
        population: "218269"
    },
    {
        city: "Kigoma",
        admin: "Kigoma",
        country: "Tanzania",
        population_proper: "164268",
        iso2: "TZ",
        capital: "admin",
        lat: "-4.876944",
        lng: "29.626667",
        population: "164268"
    },
    {
        city: "Tabora",
        admin: "Tabora",
        country: "Tanzania",
        population_proper: "145292",
        iso2: "TZ",
        capital: "admin",
        lat: "-5.016667",
        lng: "32.8",
        population: "146495"
    },
    {
        city: "Musoma",
        admin: "Mara",
        country: "Tanzania",
        population_proper: "121119",
        iso2: "TZ",
        capital: "admin",
        lat: "-1.5",
        lng: "33.8",
        population: "133156"
    },
    {
        city: "Tukuyu",
        admin: "Mbeya",
        country: "Tanzania",
        population_proper: "28398",
        iso2: "TZ",
        capital: "",
        lat: "-9.25",
        lng: "33.65",
        population: "127570"
    },
    {
        city: "Songea",
        admin: "Ruvuma",
        country: "Tanzania",
        population_proper: "115397",
        iso2: "TZ",
        capital: "admin",
        lat: "-10.683333",
        lng: "35.65",
        population: "126449"
    },
    {
        city: "Iringa",
        admin: "Iringa",
        country: "Tanzania",
        population_proper: "94760",
        iso2: "TZ",
        capital: "admin",
        lat: "-7.766667",
        lng: "35.7",
        population: "111820"
    },
    {
        city: "Shinyanga",
        admin: "Shinyanga",
        country: "Tanzania",
        population_proper: "80226",
        iso2: "TZ",
        capital: "admin",
        lat: "-3.666667",
        lng: "33.433333",
        population: "107362"
    },
    {
        city: "Bukoba",
        admin: "Kagera",
        country: "Tanzania",
        population_proper: "70628",
        iso2: "TZ",
        capital: "admin",
        lat: "-1.331667",
        lng: "31.812222",
        population: "100504"
    },
    {
        city: "Mtwara",
        admin: "Mtwara",
        country: "Tanzania",
        population_proper: "86746",
        iso2: "TZ",
        capital: "admin",
        lat: "-10.266667",
        lng: "40.183333",
        population: "96602"
    },
    {
        city: "Kilosa",
        admin: "Morogoro",
        country: "Tanzania",
        population_proper: "13227",
        iso2: "TZ",
        capital: "",
        lat: "-6.833333",
        lng: "36.983333",
        population: "91889"
    },
    {
        city: "Sumbawanga",
        admin: "Rukwa",
        country: "Tanzania",
        population_proper: "63932",
        iso2: "TZ",
        capital: "admin",
        lat: "-7.966667",
        lng: "31.616667",
        population: "89161"
    },
    {
        city: "Bagamoyo",
        admin: "Coast",
        country: "Tanzania",
        population_proper: "793",
        iso2: "TZ",
        capital: "",
        lat: "-6.433333",
        lng: "38.9",
        population: "82426"
    },
    {
        city: "Uvinza",
        admin: "Kigoma",
        country: "Tanzania",
        population_proper: "24650",
        iso2: "TZ",
        capital: "",
        lat: "-5.103611",
        lng: "30.391111",
        population: "80350"
    },
    {
        city: "Mpanda",
        admin: "Katavi",
        country: "Tanzania",
        population_proper: "73338",
        iso2: "TZ",
        capital: "",
        lat: "-6.365464",
        lng: "31.040911",
        population: "73338"
    },
    {
        city: "Singida",
        admin: "Singida",
        country: "Tanzania",
        population_proper: "33067",
        iso2: "TZ",
        capital: "admin",
        lat: "-4.816667",
        lng: "34.75",
        population: "62432"
    },
    {
        city: "Korogwe",
        admin: "Tanga",
        country: "Tanzania",
        population_proper: "44000",
        iso2: "TZ",
        capital: "",
        lat: "-5.15",
        lng: "38.483333",
        population: "50000"
    },
    {
        city: "Chake Chake",
        admin: "Pemba South",
        country: "Tanzania",
        population_proper: "21686",
        iso2: "TZ",
        capital: "admin",
        lat: "-5.25",
        lng: "39.766667",
        population: "49959"
    },
    {
        city: "Ifakara",
        admin: "Morogoro",
        country: "Tanzania",
        population_proper: "6331",
        iso2: "TZ",
        capital: "",
        lat: "-8.133333",
        lng: "36.683333",
        population: "49528"
    },
    {
        city: "Njombe",
        admin: "Njombe",
        country: "Tanzania",
        population_proper: "37311",
        iso2: "TZ",
        capital: "",
        lat: "-9.333333",
        lng: "34.766667",
        population: "46724"
    },
    {
        city: "Lindi",
        admin: "Lindi",
        country: "Tanzania",
        population_proper: "13995",
        iso2: "TZ",
        capital: "admin",
        lat: "-10.0",
        lng: "39.716667",
        population: "41912"
    },
    {
        city: "Kasulu",
        admin: "Kigoma",
        country: "Tanzania",
        population_proper: "25088",
        iso2: "TZ",
        capital: "",
        lat: "-4.576667",
        lng: "30.1025",
        population: "37349"
    },
    {
        city: "Tunduma",
        admin: "Mbeya",
        country: "Tanzania",
        population_proper: "18530",
        iso2: "TZ",
        capital: "",
        lat: "-9.3",
        lng: "32.766667",
        population: "36556"
    },
    {
        city: "Masasi",
        admin: "Mtwara",
        country: "Tanzania",
        population_proper: "27067",
        iso2: "TZ",
        capital: "",
        lat: "-10.716667",
        lng: "38.8",
        population: "36032"
    },
    {
        city: "Kahama",
        admin: "Shinyanga",
        country: "Tanzania",
        population_proper: "34544",
        iso2: "TZ",
        capital: "",
        lat: "-3.833333",
        lng: "32.6",
        population: "36014"
    },
    {
        city: "Babati",
        admin: "Manyara",
        country: "Tanzania",
        population_proper: "3943",
        iso2: "TZ",
        capital: "admin",
        lat: "-4.216667",
        lng: "35.75",
        population: "34291"
    },
    {
        city: "Biharamulo",
        admin: "Kagera",
        country: "Tanzania",
        population_proper: "9597",
        iso2: "TZ",
        capital: "",
        lat: "-2.631944",
        lng: "31.308889",
        population: "34038"
    },
    {
        city: "Kibiti",
        admin: "Coast",
        country: "Tanzania",
        population_proper: "943",
        iso2: "TZ",
        capital: "",
        lat: "-7.721785",
        lng: "38.937491",
        population: "30163"
    },
    {
        city: "Sikonge",
        admin: "Tabora",
        country: "Tanzania",
        population_proper: "1986",
        iso2: "TZ",
        capital: "",
        lat: "-5.633333",
        lng: "32.766667",
        population: "27113"
    },
    {
        city: "Nzega",
        admin: "Tabora",
        country: "Tanzania",
        population_proper: "10066",
        iso2: "TZ",
        capital: "",
        lat: "-4.216667",
        lng: "33.183333",
        population: "26584"
    },
    {
        city: "Wete",
        admin: "Pemba North",
        country: "Tanzania",
        population_proper: "26450",
        iso2: "TZ",
        capital: "admin",
        lat: "-5.066667",
        lng: "39.716667",
        population: "26450"
    },
    {
        city: "Kakonko",
        admin: "Kigoma",
        country: "Tanzania",
        population_proper: "7950",
        iso2: "TZ",
        capital: "",
        lat: "-3.282778",
        lng: "30.964167",
        population: "24688"
    },
    {
        city: "Kibaha",
        admin: "Coast",
        country: "Tanzania",
        population_proper: "23651",
        iso2: "TZ",
        capital: "admin",
        lat: "-6.766667",
        lng: "38.916667",
        population: "23651"
    },
    {
        city: "Mpwapwa",
        admin: "Dodoma",
        country: "Tanzania",
        population_proper: "381",
        iso2: "TZ",
        capital: "",
        lat: "-6.35",
        lng: "36.483333",
        population: "19806"
    },
    {
        city: "Itigi",
        admin: "Singida",
        country: "Tanzania",
        population_proper: "3357",
        iso2: "TZ",
        capital: "",
        lat: "-5.7",
        lng: "34.483333",
        population: "19711"
    },
    {
        city: "Same",
        admin: "Kilimanjaro",
        country: "Tanzania",
        population_proper: "2081",
        iso2: "TZ",
        capital: "",
        lat: "-4.066667",
        lng: "37.733333",
        population: "17455"
    },
    {
        city: "Ngara",
        admin: "Kagera",
        country: "Tanzania",
        population_proper: "4598",
        iso2: "TZ",
        capital: "",
        lat: "-2.512222",
        lng: "30.655833",
        population: "16890"
    },
    {
        city: "Mikumi",
        admin: "Morogoro",
        country: "Tanzania",
        population_proper: "8162",
        iso2: "TZ",
        capital: "",
        lat: "-7.40409",
        lng: "36.983093",
        population: "16780"
    },
    {
        city: "Karema",
        admin: "Katavi",
        country: "Tanzania",
        population_proper: "12630",
        iso2: "TZ",
        capital: "",
        lat: "-6.820516",
        lng: "30.438866",
        population: "16385"
    },
    {
        city: "Nyahanga",
        admin: "Simiyu",
        country: "Tanzania",
        population_proper: "16092",
        iso2: "TZ",
        capital: "",
        lat: "-2.383333",
        lng: "33.55",
        population: "16092"
    },
    {
        city: "Mbulu",
        admin: "Manyara",
        country: "Tanzania",
        population_proper: "7412",
        iso2: "TZ",
        capital: "",
        lat: "-3.85",
        lng: "35.533333",
        population: "13430"
    },
    {
        city: "Kilindoni",
        admin: "Coast",
        country: "Tanzania",
        population_proper: "3580",
        iso2: "TZ",
        capital: "",
        lat: "-7.9139",
        lng: "39.666842",
        population: "12409"
    },
    {
        city: "Ngorongoro",
        admin: "Arusha",
        country: "Tanzania",
        population_proper: "10836",
        iso2: "TZ",
        capital: "",
        lat: "-3.25",
        lng: "35.516667",
        population: "10836"
    },
    {
        city: "Mbamba Bay",
        admin: "Ruvuma",
        country: "Tanzania",
        population_proper: "8997",
        iso2: "TZ",
        capital: "",
        lat: "-11.283333",
        lng: "34.766667",
        population: "8997"
    },
    {
        city: "Oldeani",
        admin: "Arusha",
        country: "Tanzania",
        population_proper: "6601",
        iso2: "TZ",
        capital: "",
        lat: "-3.35",
        lng: "35.55",
        population: "8000"
    },
    {
        city: "Mkokotoni",
        admin: "Zanzibar North",
        country: "Tanzania",
        population_proper: "2572",
        iso2: "TZ",
        capital: "admin",
        lat: "-5.866667",
        lng: "39.25",
        population: "2572"
    },
    {
        city: "Geita",
        admin: "Geita",
        country: "Tanzania",
        population_proper: "1536",
        iso2: "TZ",
        capital: "",
        lat: "-2.866667",
        lng: "32.166667",
        population: "1536"
    },
    {
        city: "Kipili",
        admin: "Rukwa",
        country: "Tanzania",
        population_proper: "1533",
        iso2: "TZ",
        capital: "",
        lat: "-7.433333",
        lng: "30.6",
        population: "1533"
    },
    {
        city: "Tunduru",
        admin: "Ruvuma",
        country: "Tanzania",
        population_proper: "600",
        iso2: "TZ",
        capital: "",
        lat: "-11.066667",
        lng: "37.35",
        population: "600"
    },
    {
        city: "Manyoni",
        admin: "Singida",
        country: "Tanzania",
        population_proper: "310",
        iso2: "TZ",
        capital: "",
        lat: "-5.75",
        lng: "34.833333",
        population: "310"
    },
    {
        city: "Kanyato",
        admin: "Kigoma",
        country: "Tanzania",
        population_proper: "232",
        iso2: "TZ",
        capital: "",
        lat: "-4.456944",
        lng: "30.261389",
        population: "232"
    },
    {
        city: "Koani",
        admin: "Zanzibar Central/South",
        country: "Tanzania",
        population_proper: "",
        iso2: "TZ",
        capital: "admin",
        lat: "-6.133333",
        lng: "39.283333",
        population: ""
    }
];


locations.forEach((l, i) => {
    locations[i].id = l.city.split(" ").join("_").toLowerCase()
})

module.exports = locations